In [50]:
from sklearn import model_selection
from sklearn import metrics
from scipy import stats
import seaborn as sns
import pandas as pd
import numpy as np
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from scipy.stats import zscore
import matplotlib.pyplot as plt
from sklearn import svm

In [51]:
myfile_df=pd.read_csv("C:\\Users\\Hp\\Downloads\\Dataset_m_top_final.csv")
myfile_df

,ImgID,BodySize,Complexion,Occasion,DressColor,DressDesign,Matching
0,photo-1492447166138-50c3889fccb1,L,Very Fair,Casual,Black&White,Cuban Collar Shirt,Y
1,Img_4,XL,Fair,Casual,Blue&White,Linen Shirt,N
2,image_51,M,Medium,Casual,LightBlue,Overshirt,N
3,image_52,M,Very Fair,Casual,Muddy Brown,Linen Shirt,Y
4,image_53,S,Fair,Wedding,White&Pink,Overshirt,Y
...,...,...,...,...,...,...,...
350,IMG-rgvghvejgfj34f,XL,Olive,Party,Blue&White,Oxford Button-Down Shirt,N
351,IMG-hj hbjjgfj34f,S,Very Fair,Formal,White,Classic Short Sleeve Shirt,Y
352,IMG-vtyvvhhjhbjbbb,L,Medium,Casual,Blue&White,Casual Shirts,N
353,IMG-r98389r4f,XL,Fair,Sports,White,Oxford Button-Down Shirt,Y
354,IMG-773bexuwubw,XL,Brown,Sports,Blue,Classic Short Sleeve Shirt,Y

In [52]:
myfile_df.columns

Index(['ImgID', 'BodySize', 'Complexion', 'Occasion', 'DressColor',
       'DressDesign', 'Matching'],
      dtype='object')

In [53]:
myfile_df.shape

(355, 7)

In [54]:
myfile_df.dtypes

ImgID          object
BodySize       object
Complexion     object
Occasion       object
DressColor     object
DressDesign    object
Matching       object
dtype: object

In [55]:
myfile_df['Matching'].value_counts()

Y    229
N    126
Name: Matching, dtype: int64

In [56]:
myfile_df=myfile_df.drop('ImgID' , axis=1)

In [57]:
myfile_df['BodySize']=myfile_df.BodySize.astype('category')
myfile_df['Complexion']=myfile_df.Complexion.astype('category')
myfile_df['Occasion']=myfile_df.Occasion.astype('category')
myfile_df['DressColor']=myfile_df.DressColor.astype('category')
myfile_df['DressDesign']=myfile_df.DressDesign.astype('category')
myfile_df['Matching']=myfile_df.Matching.astype('category')
myfile_df.dtypes

BodySize       category
Complexion     category
Occasion       category
DressColor     category
DressDesign    category
Matching       category
dtype: object

In [58]:
myfile_df[myfile_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [BodySize, Complexion, Occasion, DressColor, DressDesign, Matching]
Index: []

In [59]:
myfile_df.iloc[60:90]

,BodySize,Complexion,Occasion,DressColor,DressDesign,Matching
60,XL,Very Fair,Casual,Blue&White,Flannel Shirt,Y
61,XL,Brown,Casual,Black&White,Flannel Shirt,Y
62,XL,Dark Brown,Casual,Blue&Pink,Flannel Shirt,Y
63,XXL,Olive,Casual,Multicolor,Classic Short Sleeve Shirt,N
64,XXL,Fair,Casual,Muddy Brown,Flannel Shirt,N
65,XL,Very Fair,Casual,Black&White,Flannel Shirt,Y
66,M,Olive,Casual,Blue&Red&Grey,Classic Short Sleeve Shirt,Y
67,L,Medium,Wedding,Black&Mehendi,Kurti,Y
68,XXL,Fair,Wedding,Cream,Kurti,Y
69,XXL,Medium,Wedding,Blue&White&Grey,Kurti,Y
70,L,Brown,Wedding,Blue&White,Kurti,Y
71,XL,Very Fair,Wedding,Grey&White,Kurti,Y
72,L,Dark Brown,Wedding,Blue&MuddyBrown,Kurti,Y
73,XXL,Brown,Wedding,Black&White,Kurti,Y
74,XL,Medium,Wedding,DarkBlue&White,Kurti,Y
75,XXL,Olive,Wedding,White&Blue,Kurti,Y
76,XXL,Brown,Wedding,Pink&Black,Kurti,Y
77,L,Fair,Formal,White&Grey,T Shirt,Y
78,L,Medium,Formal,Pink&Grey,Flannel Shirt,Y
79,XL,Very Fair,Formal,Pink&Black,Full Shirt,N
80,XL,Brown,Formal,Blue,Flannel Shirt,N
81,XXL,Olive,Formal,Red&Black,Overshirt,Y
82,XXL,Fair,Formal,Red&Grey,Half Kurti,Y
83,XL,Fair,Formal,Blue&grey,Half Polo Shirt,N
84,L,Brown,Formal,Black&White,Flannel Shirt,Y
85,L,Fair,Formal,Blue&White,Flannel Shirt,Y
86,XL,Very Fair,Formal,Black&White,Flannel Shirt&Half blazer,N
87,L,Olive,Sports,Blue&Pink,Sport jacket,N
88,M,Medium,Sports,Multicolor,Half Polo Shirt,Y
89,L,Olive,Sports,Muddy Brown,Sport jacket,N

In [60]:
myfile_df.describe().transpose()

            count unique          top freq
BodySize      355      6           XL  154
Complexion    355      6         Fair   94
Occasion      355      8       Casual  141
DressColor    355     75        Black   45
DressDesign   355     27  Linen Shirt   69
Matching      355      2            Y  229

In [61]:
myfile_df.groupby(["Matching"]).count()

          BodySize  Complexion  Occasion  DressColor  DressDesign
Matching
N              126         126       126         126          126
Y              229         229       229         229          229

In [62]:
myfile_df=myfile_df.drop('Matching', axis=1)

In [63]:
myfile_df.shape

(355, 5)

In [64]:
myfile_df=pd.get_dummies(myfile_df)
myfile_df

,BodySize_L,BodySize_M,BodySize_S,BodySize_XL,BodySize_XS,BodySize_XXL,Complexion_Brown,Complexion_Dark Brown,Complexion_Fair,Complexion_Medium,...,DressDesign_Kurti,DressDesign_Linen Shirt,DressDesign_Overshirt,DressDesign_Oxford Button-Down Shirt,DressDesign_Polo Shirt,DressDesign_Round Neck,DressDesign_Sflannel Shirt,DressDesign_Sport jacket,DressDesign_T Shirt,DressDesign_Winter Wear
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
353,0,0,0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
354,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [65]:
myfile_df_dummy=pd.get_dummies(myfile_df,drop_first=True)
myfile_df_dummy

,BodySize_L,BodySize_M,BodySize_S,BodySize_XL,BodySize_XS,BodySize_XXL,Complexion_Brown,Complexion_Dark Brown,Complexion_Fair,Complexion_Medium,...,DressDesign_Kurti,DressDesign_Linen Shirt,DressDesign_Overshirt,DressDesign_Oxford Button-Down Shirt,DressDesign_Polo Shirt,DressDesign_Round Neck,DressDesign_Sflannel Shirt,DressDesign_Sport jacket,DressDesign_T Shirt,DressDesign_Winter Wear
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
353,0,0,0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
354,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
x=np.array(myfile_df)
x

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [67]:
y=np.array(myfile_df)
y

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [68]:
array=myfile_df.values
x=array[:,0:5]
y=array[:,5]

In [69]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [70]:
x_train.shape

(284, 5)

In [71]:
x_test.shape

(71, 5)

In [72]:
y_train.shape

(284,)

In [73]:
y_test.shape

(71,)

In [74]:
print(type (x_train))
print(type (x_test))
print(type (y_train))
print(type (y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [75]:
model=LogisticRegression()
model.fit(x_train, y_train)
y_predict=model.predict(x_test)
model_score=model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.9859154929577465
[[59  1]
 [ 0 11]]

# KNN METHOD

In [76]:
NNH=KNeighborsClassifier(n_neighbors=5 , weights='distance')

In [77]:
NNH.fit(x_train, y_train)

KNeighborsClassifier(weights='distance')

In [78]:
predicted_lables = NNH.predict(x_test)
NNH.score(x_test, y_test)

0.9859154929577465

In [79]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predicted_lables))

[[59  1]
 [ 0 11]]

In [80]:
from sklearn.neighbors import KNeighborsClassifier
Classifier= KNeighborsClassifier(n_neighbors=5,  weights='distance')
Classifier.fit(x_train, y_train)

KNeighborsClassifier(weights='distance')

In [81]:
y_pred=Classifier.predict(x_test)

In [82]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        60
           1       0.92      1.00      0.96        11

    accuracy                           0.99        71
   macro avg       0.96      0.99      0.97        71
weighted avg       0.99      0.99      0.99        71

[[59  1]
 [ 0 11]]

# SVM

In [83]:
classifier=svm.SVC(kernel='linear', gamma='auto', C=2)
classifier.fit(x_train, y_train,) 
y_predict=classifier.predict(x_test)

In [84]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        60
           1       0.92      1.00      0.96        11

    accuracy                           0.99        71
   macro avg       0.96      0.99      0.97        71
weighted avg       0.99      0.99      0.99        71

In [85]:
print(y_predict)

[0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0]

In [86]:
classifier.score(x_test,y_test)

0.9859154929577465